<a href="https://colab.research.google.com/github/Vishal-Dhoriya/woc5.0-ml-weather-prediction-case-study-Vishal/blob/main/WOC5.0_ML_Checkpoint_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Numpy***

In [1]:
import numpy as np

In [2]:
myarr = np.array([1,2,3],np.int8)
print(myarr)

[1 2 3]


In [3]:
myarr.shape


(3,)

In [4]:
myarr.dtype

dtype('int8')

In [5]:
arr = np.array([[1,2,3,4]])

In [6]:
arr

array([[1, 2, 3, 4]])

In [7]:
arr[0,1]

2

In [8]:
arr[0,1] = 7

In [9]:
arr[0,1]

7

In [10]:
# there are 5 types for creating numpy array

In [11]:
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# making dtype  = object is not widely used

In [15]:
listarr.shape

(3, 3)

In [16]:
listarr.dtype

dtype('int64')

In [17]:
listarr.size

9

In [18]:
#it is not efficient to make a dtype object

In [20]:
zeros  = np.zeros((2,5))

In [21]:
zeros.shape

(2, 5)

In [22]:
rng = np.arange(15)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace = np.linspace(1,5,5)

In [25]:
lspace

array([1., 2., 3., 4., 5.])

In [27]:
emp = np.empty((2,6))

In [28]:
emp
#this empty thing just creates array with a random valued array

array([[0.00000000e+000, 6.79038654e-313, 6.79038653e-313,
        2.37663529e-312, 2.14321575e-312, 2.37663529e-312],
       [2.56761491e-312, 1.06099790e-312, 1.14587773e-312,
        2.14321575e-312, 3.99910963e+252, 1.46030983e-319]])

In [29]:
ide = np.identity(12)

In [31]:
ide
#this gives an array of 12 *(cross) 12 identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
ide.shape

(12, 12)

In [34]:
re  = np.arange(99)

In [35]:
re.reshape(3,33)
#reshape is allowed but the desired matrix must have the same number of elements as that of the initial array 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [69]:
re=re.ravel()

In [41]:
re.shape

(99,)

In [42]:
#numpy axis -->axis starts with 0 nuumber

In [43]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [45]:
ar =np.array(x)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
ar.sum(axis = 0)
# axis  = 0 represent the columns

array([12, 15, 18])

In [51]:
ar.sum(axis = 1)
# axis = 1 represent the rows

array([ 6, 15, 24])

In [52]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
ar.flat
#this thing gives us an iterator

In [57]:
for item in ar.flat:
    print(item)
    #usiing the iterator created earlier now we will iterate the whole ar array

1
2
3
4
5
6
7
8
9


In [58]:
ar.ndim
#it gives us the number of the dimensions

2

In [61]:
ar.size
#shows us the number of total elements in the array

9

In [62]:
ar.nbytes
#lets us know how many total bytes are consumed

72

In [63]:
#if brackets are not present that means that they are attributes , if braces are present they we are using it as a function

In [65]:
ar.argmax()
#this gives us the index having the largest element ,lly we are having argmin to get the minimum value

8

In [67]:
ar.argsort()
#this gives us the indexes in the sorted order

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [68]:
#matrix addition and multiplication of two arrays is also possible 
#lly we have other fun like sqrt which does square rootof each element of array
#to find elements in array we can use np.where(condition for finding the element)
# to count the number of non zero elements in a array use np.count_nonzero(array_name)
#but if we use np.nonzero(array_name) it returns us a tuple for every dim